name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  validate:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jsonschema
      
      - name: Getting schema
        run: |
          curl -O https://raw.githubusercontent.com/jsonresume/resume-schema/master/schema.json
      
      - name: Validating resume
        run: |
          jsonschema --instance resume.json schema.json

  render:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Create files
        run: |
          python generate.py --overwrite
          
          
      
